name: "Setup Git"
description: "Setup Git Authentication Information"
inputs:
  username:
    description: "Git Username"
  email:
    description: "Git Email"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.username }}
    - ${{ inputs.email }}
